deploy:
  - provider: s3
    cache_control: "no-cache, max-age=0" # cache and revalidate
    access_key_id: $AWS_ACCESS
    secret_access_key: $AWS_SECRET
    bucket: $BUCKET_DEV
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: "develop"
  - provider: s3
    cache_control: "max-age=2592000" # 30 days
    access_key_id: $AWS_ACCESS
    secret_access_key: $AWS_SECRET
    bucket: $BUCKET_PROD
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: "master"
language: node_js
node_js:
  - "lts/*"
install: yarn
script:
  - yarn run build
  - yarn test
warnings_are_errors: false
cache:
  yarn: true
  directories:
    - node_modules
